export const data = [
  {
    id: "pp1",
    title: "Sufferer",
    description: "A social media web application",
    visitLink:"https://sufferer.vercel.app/",
    points: [
      "Node.js, Next.js, Tailwind CSS, MongoDB",
      "Implemented secure user authentication and authorization.",
      "Applied strategies for faster page load times.",
    ],
    link: "/images/suffererBg.png",
  },
  {
    id: "pp2",
    title: "Grovy",
    description: "My Personal Library",
    visitLink:"https://grovy.vercel.app/",
    points: [
      "Firebase, Next.js, Tailwind CSS, shadcn, Zod",
      "Manage your all type of files on cloud (size based)",
      "Create, Mover, Delete your categories and tasks based on them.",
    ],
    link: "/images/grovyBg.png",
  },
  {
    id: "pp3",
    title: "Picture Print",
    visitLink:"https://pictureprint.vercel.app/",
    description: "Pdf manupulation web app",
    points: [
      "Implemented functionality to extract images from PDF documents",
      "Developed a tool for converting images into PDF files.",
      "Generated a diverse range of random images for versatile use.",
    ],
    link: "/images/picturePrintBg.png",
  },
  {
    id: "pp4",
    title: "SideCup Family Golf",
    visitLink:"https://github.com/Shivam bishnoi156/sports-website",
    description: "A Learning Project",
    points: [
      "Cloned an interective existing sports website",
      "Learned how to use gsap different than usual",
      "Learned different types of styling the structure",
    ],
    link: "/images/sideCupBg.png",
  },
  {
    id: "pp5",
    title: "Ink Map",
    visitLink:"https://github.com/Shivam bishnoi156/InkMap",
    description: "Save Your Tasks Limitlessly",
    points: [
      "Designed an fully functional task saving web app",
      "Learned how to use context api in react",
      "Reduced the number of api calls by 40% by using local storage",
    ],
    link: "/images/inkMapBg.png",
  },
  {
    id: "pp6",
    title: "New Monkey",
    visitLink:"https://github.com/Shivam bishnoi156/NewsApp-Classbased",
    description: "Fetch latest news anytime",
    points: [
      "Used news api to fetch news and articles",
      "Impletented Infinite Scroll on news for infinite scrolling",
      "Implemented different categories of fetching and showcasing data",
    ],
    link: "/images/newsMonkeyBg.png",
  },
  {
    id: "pp7",
    title: "Pass Gen",
    visitLink:"https://Shivam bishnoi156.github.io/PASS-GEN/",
    description: "My own password generation web app",
    points: [
      "Implemented advance css animations",
      "Structured an responsive website with all the animations",
      "Learned regular expressions by generating strong password",
    ],
    link: "/images/passGenBg.png",
  },
];
